### ISSUE TITLE
MAX MAP LIMITS

### ISSUE THREAD

**Issue by Heyter** [Nak2/NikNaks#15]
Feb 2019

* MAX_MAP_ENTITIES - 8192 to 20480
* MAX_MAP_AREAS - 256 to 1024
* MAX_MAP_BRUSHES - 8192 to 16384
* MAX_NODES - 1500 to 4096
* MAX_MAP_BRUSHSIDES - 65536 to 163840
* Displacements - 2048 to 5500

https://github.com/Nak2/NikNaks/blob/main/lua/niknaks/modules/sh_bsp_brushes.lua#L19C1-L20C33

**Comment by Nak2** [comment]
Sorry for leaving this for so long. I've increased the max variables.
