### ISSUE TITLE
Some navmeshes seem to cause a memory leak on generation

### ISSUE THREAD

**Issue by riftkan** [Nak2/NikNaks#2]
https://steamcommunity.com/workshop/filedetails/?id=169600867
https://steamcommunity.com/sharedfiles/filedetails/?id=1722381233

Gmod essentially dies trying to load into this map if this navmesh is enabled, not entirely sure why. Gmod ends up in this loop where it continuously eats up 23 gigs of memory, then dumps it all.

**Comment by Nak2** [comment]
This feature has been removed from NikNaks. While nice, it had a lot of issues and quickly ran out of memory on larger maps.
If I find a way to utilize the bitbuffer to lower the memory usage, I may revisit this.

Sry for taking this long.
