### ISSUE TITLE
There is no method "Has3DSkyInPVS"

### ISSUE THREAD

**Issue by ts-co** [Nak2/NikNaks#9]
Tried calling a function like this:
`lua_run print(NikNaks.CurrentMap:IsRenderingSkyboxAtPosition(player.GetAll()[1]:GetPos()))`

Received this error:
```
[NikNaks] lua/niknaks/modules/sh_bsp_module.lua:1066: attempt to call method 'Has3DSkyInPVS' (a nil value)
  1. IsRenderingSkyboxAtPosition - lua/niknaks/modules/sh_bsp_module.lua:1066
   2. unknown - lua_run:1
```

Couldn't seem to find that function in the GitHub repo either.

**Comment by Nak2** [comment]
Sry for taking so long.

There where a few issues regarding the IsRenderingSkyboxAtPosition back then, but it should be solved now.
![billede](https://github.com/user-attachments/assets/ede2fd0e-d927-4cb8-bc05-c2cdf01edd0b)

Feel free to reopen if the issue is still there.
